#!/usr/bin/env python3
"""Build TFT_eSPI smooth fonts (.vlw) from a TTF, and the C headers that embed them.

TFT_eSPI reads the Processing .vlw format:

    header:  6 big endian int32  - glyph count, version, yAdvance, unused,
                                   ascent, descent
    glyphs:  7 big endian int32 each - unicode, height, width, xAdvance,
                                   dY (top above baseline), dX (left bearing), unused
    bitmaps: one byte of coverage per pixel, row major, in glyph order

Usage:
    make_vlw.py FONT.ttf SIZE OUTPUT_NAME [--chars STRING]
"""
import argparse
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

DEFAULT_CHARS = "".join(chr(c) for c in range(32, 127))


def glyph_bitmap(font, char, ascent, descent):
    box = font.getbbox(char)
    if box is None:
        box = (0, 0, 0, 0)
    x0, y0, x1, y1 = box
    width, height = max(0, x1 - x0), max(0, y1 - y0)
    advance = int(round(font.getlength(char)))
    if width == 0 or height == 0:
        return b"", 0, 0, advance, 0, 0
    canvas = Image.new("L", (x1 + 8, ascent + descent + 8), 0)
    ImageDraw.Draw(canvas).text((0, 0), char, font=font, fill=255, anchor="la")
    crop = canvas.crop((x0, y0, x1, y1))
    # dY is measured up from the baseline, y0 is measured down from the ascender.
    return crop.tobytes(), width, height, advance, ascent - y0, x0


def build(ttf, size, chars):
    font = ImageFont.truetype(str(ttf), size)
    ascent, descent = font.getmetrics()
    header, table, bitmaps = [], [], []
    for char in chars:
        data, width, height, advance, dy, dx = glyph_bitmap(font, char, ascent, descent)
        table.append(struct.pack(">7i", ord(char), height, width, advance, dy, dx, 0))
        bitmaps.append(data)
    header = struct.pack(">6i", len(chars), 11, ascent + descent, 0, ascent, descent)
    return header + b"".join(table) + b"".join(bitmaps)


def write_header(blob, name, path):
    lines = [f"// Generated by tools/make_vlw.py. Do not edit by hand.",
             f"#pragma once",
             f"#include <pgmspace.h>",
             f"",
             f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(blob), 16):
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in blob[i:i + 16]) + ",")
    lines += ["};", ""]
    path.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("ttf")
    parser.add_argument("size", type=int)
    parser.add_argument("name")
    parser.add_argument("--chars", default=DEFAULT_CHARS)
    parser.add_argument("--outdir", default=".")
    args = parser.parse_args()

    blob = build(Path(args.ttf), args.size, args.chars)
    outdir = Path(args.outdir)
    (outdir / f"{args.name}.vlw").write_bytes(blob)
    write_header(blob, args.name, outdir / f"{args.name}.h")
    print(f"{args.name}: {len(args.chars)} glyphs, {len(blob)} bytes")


if __name__ == "__main__":
    main()
