[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI
  paulstoffregen/XPT2046_Touchscreen
  bblanchon/ArduinoJson
build_flags =
  -D USER_SETUP_LOADED=1
  -include include/tft_setup.h
